default: &default
  users:
    url: http://1.2.3.4:7711/api/v1/
  posts:
    url: http://1.2.3.4:8383/api/v1/
  locally:
    url: http://localhost:8383/api/v1/
  pompa_service:
    url: http://localhost:8383/api/v1/


development: &development
<<: *default

production: &production
  <<: *default
  users:
    url: http://1.2.3.4:7711/api/v0/
  posts:
    url: http://1.2.3.4:8383/api/v0/
  locally:
    url: http://localhost:8383/api/v0/